[package]
authors = { workspace = true }
description = "Core Blockchain ETL binary."
edition = { workspace = true }
homepage = { workspace = true }
keywords = ["core blockchain", "xcb", "etl"]
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
name = "core-etl-bin"
publish = true

[[bin]]
name = "core-etl"
path = "src/main.rs"

[dependencies]
config.workspace = true
etl.workspace = true
provider.workspace = true
mock_storage.workspace = true
storage.workspace = true
sqlite3_storage.workspace = true
postgres_storage.workspace = true
types.workspace = true

anyhow.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
  "ansi",
  "env-filter",
  "json",
] }

clap.workspace = true
clap_complete.workspace = true
clap_complete_fig.workspace = true
dotenvy = { version = "0.15" }

atoms-rpc-types.workspace = true
